### ISSUE TITLE
How to install rdss?

### ISSUE THREAD

**Issue by oscci** [DeclareDesign/rdddr#7]
I discovered _rdddr_ no longer was available, and it looks like I need _rdss_ instead, but it's not available on CRAN.
Also, this "getting started" page still references _rdddr_, which is going to be offputting for newbies : https://declaredesign.org/getting-started/
Thanks.

**Comment by macartan** [comment]
Thanks Dorothy!
We’ll have to fix the getting started page
rdss should be back up any day now, sorry for the interruption; in the
meantime this should work:

remotes::install_github("DeclareDesign/rdss")

**Comment by oscci** [comment]
Thanks. All good. 
I'm finding DeclareDesign v useful for demonstrating how posthoc selection of participants for an analysis creates bias.

**Comment by graemeblair** [comment]
Thanks Dorothy. You can now install rdss in the usual way!
